version: "2"
services:
  samples-account:
    image: samples-account:1.0.0
    container_name: samples-account
    ports:
    - "8102:8102"
    external_links:
    - nacos
    - fescar
    - mysql
  samples-storage:
    image: samples-storage:1.0.0
    container_name: samples-storage
    ports:
    - "8100:8100"
    external_links:
    - nacos
    - fescar
    - mysql
networks:
  default:
    external:
      name: app_net
